import { useState } from 'react'
import { supabase } from '../../services/supabaseClient'

type Props = { lang: 'es' | 'en' }
type Result = { label: string; passed: boolean }
const BUCKET = 'post-photos'
const PNG_1PX = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+wZ4sAAAAASUVORK5CYII='
const isTrialPath = (path: string, uid: string) =>
  new RegExp('^' + uid.replace(/-/g, '\\-') + '/f14-storage-probe-[0-9a-f-]{36}\\.png$', 'i').test(path)
const testFile = () => {
  const binary = atob(PNG_1PX)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return new Blob([bytes.buffer as ArrayBuffer], { type: 'image/png' })
}

/** Preview-only: user-initiated synthetic Storage API smoke, no real user content. */
export function F14StorageProbe({ lang }: Props) {
  const es = lang === 'es'
  const [busy, setBusy] = useState(false)
  const [steps, setSteps] = useState<Result[]>([])
  const [error, setError] = useState('')
  const [completed, setCompleted] = useState(false)

  const run = async () => {
    if (busy) return
    setBusy(true)
    setCompleted(false)
    setSteps([])
    setError('')
    let path = ''
    let savedKey = ''
    let stepsDone: Result[] = []
    const add = (label: string) => {
      stepsDone = [...stepsDone, { label, passed: true }]
      setSteps(stepsDone)
    }
    try {
      const { data, error: authError } = await supabase.auth.getUser()
      if (authError || !data.user) throw new Error('auth')
      const uid = data.user.id
      savedKey = 'pazo:f14:storage-probe:' + uid
      const stored = window.sessionStorage.getItem(savedKey)
      if (stored && !isTrialPath(stored, uid)) throw new Error('invalid_saved_path')
      path = stored || uid + '/f14-storage-probe-' + crypto.randomUUID() + '.png'
      add(es ? 'Cuenta autenticada' : 'Authenticated account')
      const storage = supabase.storage.from(BUCKET)
      if (!stored) {
        // Save path BEFORE upload so any interruption is recoverable.
        window.sessionStorage.setItem(savedKey, path)
        const upload = await storage.upload(path, testFile(), {
          cacheControl: '60', upsert: false, contentType: 'image/png'
        })
        if (upload.error) throw new Error('upload')
        add(es ? 'Imagen sintética creada' : 'Synthetic image uploaded')
        const info = await storage.info(path)
        if (info.error || !info.data || !Number.isFinite(info.data.size) || info.data.size <= 0)
          throw new Error('info')
        add(es ? 'Archivo comprobado mediante Storage API' : 'File verified by Storage API')
      } else {
        add(es ? 'Reanudando limpieza del archivo sintético anterior' : 'Resuming previous synthetic fixture cleanup')
      }
      // Exactly one path generated by this test. No user-provided paths accepted.
      if (!isTrialPath(path, uid)) throw new Error('invalid_path')
      const removed = await storage.remove([path])
      if (removed.error) throw new Error('remove')
      // Rely on absence observed by the Storage origin API, not success text alone.
      const checked = await storage.info(path)
      const notFound = !!checked.error && String(checked.error.statusCode) === '404'
      if (!notFound) throw new Error('not_verified_absent')
      add(es ? 'Ausencia del archivo confirmada en Storage' : 'Storage object absence confirmed')
      window.sessionStorage.removeItem(savedKey)
      setCompleted(true)
    } catch {
      // If a request failed, the saved path is retained to allow safe cleanup
      // on the next press; the next attempt DOES NOT upload a second file.
      setError(es
        ? 'No se pudo verificar todo el proceso. No repitas con otra cuenta; vuelve a pulsar para intentar limpiar únicamente este archivo de prueba.'
        : 'The full check could not be verified. Retry with the same account to clean up this test file only.')
    } finally {
      setBusy(false)
    }
  }

  return <section aria-label="F14 Storage API smoke" className="mb-5 rounded-2xl border border-[#204E4A]/20 bg-white p-4 text-[#204E4A]">
    <h3 className="text-sm font-extrabold">{es ? 'Prueba aislada de Storage F14' : 'Isolated F14 Storage test'}</h3>
    <p className="mt-1 text-xs leading-relaxed">
      {es
        ? 'Esta prueba crea una imagen artificial de 1 píxel y elimina solamente ese archivo de prueba. No modifica mascotas, publicaciones ni fotografías personales. No comprueba todavía la caché CDN.'
        : 'This creates a synthetic 1-pixel image and deletes only that exact test file. No personal posts or photos are changed. CDN cache is not tested.'}
    </p>
    <button type="button" disabled={busy || completed} onClick={() => void run()}
      className="mt-3 min-h-11 rounded-xl bg-[#204E4A] px-4 text-xs font-bold text-white disabled:opacity-60">
      {busy ? (es ? 'Comprobando…' : 'Checking…') : completed
        ? (es ? 'Prueba completada' : 'Test completed')
        : (es ? 'Crear, verificar y limpiar archivo de prueba' : 'Create, verify and clean test file')}
    </button>
    {steps.length > 0 && <div aria-live="polite" className="mt-3 space-y-1">
      {steps.map(step => <p key={step.label} className="text-xs text-emerald-700">PASS · {step.label}</p>)}
    </div>}
    {completed && <p className="mt-3 text-sm font-bold text-emerald-700">
      {es ? 'PASS — Archivo sintético eliminado y ausencia comprobada.' : 'PASS — Synthetic file removed and absence verified.'}
    </p>}
    {error && <p role="alert" className="mt-3 text-xs font-semibold text-red-700">{error}</p>}
    <p className="mt-2 text-[11px] opacity-75">
      {es ? 'No envía contraseñas ni tokens a servicios externos.' : 'No passwords or tokens are sent to outside services.'}
    </p>
  </section>
}
